
language: node_js
node_js:
  - 10.13.0
services:
- postgresql
env:
- SECRET = 4567yul667
branches:
  only: 
    - develop
before_script: travis_wait npm run custom-test
after_success: npm run coverage