FORMAT: 1A
HOST: https://epic-mail02.herokuapp.com/

# Epic Mail

A web app that helps people exchange messages/information over the internet.
### Required Features
* Users can sign up.
* Users can login.
* Users can create groups.
* Users can send a message to individuals.
* Users can view their inbox and read messages.
* Users can retract sent messages.
* Users can save an email as draft and send it later or delete it.

## Welcome Page [/]

###  Welcome a User [GET]
* Welcomes a user to the API

+ Response 200 (application/json)

            {
               'Visit /api/v1 to view API cheers!!!';
            }

## Signup [/auth/signup]

### Create a New User [POST]
* Creates a new user

+ Request (application/json)

        {
            email: 'ochowo@gmail.com',
            firstName: 'Ochowo',
            lastName: 'Ikongbeh',
             password: 'password',
        }

+ Response 201 (application/json)

    + Headers

            Location: /auth/signup

    + Body

            {
            "status": 201,
            "data": [
            {
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9jaG93b0BnbWFpbC5jb20iLCJ1c2VySWQiOiIzIiwiaWF0IjoxNTUxOTg0MjA2LCJleHAiOjE1NTIwNzA2MDZ9.eMkNZTXmtn-t5Mqd5-vhJITydZt8Wz_2pE6xJZmIj6M",
            "user": {
                "id": 1,                
                "email": "ochowo@gmail.com",
                "firstName": "Ochowo",
                "lastName": "Ikongbeh",
                "password": "$2b$10$DSnEJ0tF0SRZlod3h/UrYeEGfkwFjGQGI4UTHe2loWHsyI.VFDSue",
            }
            }
            ]
            }
## Login [/auth/login]

### Login a User [POST]
* Login an existing user

+ Request (application/json)

        {
            email: 'ochowo@gmail.com',
            password: 'password',
        }

+ Response 200 (application/json)

    + Headers

            Location: /auth/login

    + Body

            {
            "status": 200,
            "data": [
            {
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9jaG93b0BnbWFpbC5jb20iLCJ1c2VySWQiOiIzIiwiaWF0IjoxNTUxOTg0NTk4LCJleHAiOjE1NTIwNzA5OTh9.-UxWznzsbdpkgj6UQcv02nf_6tDy4SWnGLIeSVoGWZU",
            "userDb": {
                "id": 1,
                "email": "ochowo@gmail.com",
                "firstName": "Ochowo",
                "lastName": "Ikongbeh",
                "password": "$2b$10$DSnEJ0tF0SRZlod3h/UrYeEGfkwFjGQGI4UTHe2loWHsyI.VFDSue",
            }
            }
            ]
            }
## Messages [/messages/{?token}]

### POST an email [POST]
* Send new message 
+ Parameters
    + token (required) - User token for authentication
+ Request (application/json)

        {
            createdOn: '05, April 2018',
            subject: 'Heello',
            message: 'Nice',
            parentMessageId: '2',
            status: 'draft',
            email: 'ochowo@gmail.com',
            senderId: 1,
            receiverId: 1,
        }

+ Response 200 (application/json)

    + Headers

            Location: /messages

    + Body

            {
            "status": 201,
            "data": [{
            "message": "redflag created",
            "message": {
                "id": 4,
                "createdOn": "Thu Mar 07 2019",
                "subject": "Hello",
                "message": "Nice",
                "parentMessageId": "2",
                "status": "draft",
                "email": "ochowo@gmail.com",
                "senderId": "1",
                "receiverId": "1"
            }
            }]
            }
### Fetch all received Messages [GET]
* Get all received messages
+ Parameters
    + token (required) - User token for authentication

+ Response 200 (application/json)

        {
        "status": 200,
        "data": [
        {
        "result2": [
            {
                 "id": 1,
                "createdOn": "05, April 2018",
                "subject": "Heello",
                "message": "Nice",
                "parentMessageId": "2",
                "status": "draft",
                "email": "ochowoikongbeh@gmail.com"
            },
            {
                "id": 4,
                "createdOn": "Thu Mar 07 2019",
                "subject": "hiii",
                "message": "happy to meet you",
                "parentMessageId": "7",
                "status": "read",
                "email": "ochowo@gmail.com",
                "senderId": "3",
                "receiverId": "5"
            }
        ]
        }
        ]
        }
## Unread Message [/messages/{unread}{?token}]

### GET all Unread Message  [GET]
* Get all unread messages
+ Parameters
    + unread (required) - Message status
    + token (required) - User token for authentication
+ Response 200 (application/json)

    + Headers

            Location: /messages

    + Body

            {
            "status": 200,
            "data": [{
            "mail": {
                "id": 1,
                "createdOn": "05, April 2018",
                "subject": "Heello",
                "message": "Nice",
                "parentMessageId": "2",
                "email": "ochowoikongbeh@gmail.com"
            }
            }
            ]
            }
            }
## Sent Messages [/messages/{sent}{?token}]

### GET all Sent Message [GET]
* Get all sent messages
+ Parameters
    + sent (required) - Message status
    + token (required) - User token for authentication
+ Response 200 (application/json)

    + Headers

            Location: /messages

    + Body

            {
            "status": 200,
            "data": [{
            "mail": {
                "id": 2,
                "createdOn": "05, April 2018",
                "subject": "Heello",
                "message": "Nice",
                "parentMessageId": "2",
                "status": "sent,
                "email": "ochowoikongbeh@gmail.com"
            }
            }
            ]
            }
            }
## Specific Message [/messages/{id}{?token}]

### GET a Specific Message [GET]
* Get message with specified id 
+ Parameters
    + id (required, number, `1`) - Redflag id
    + token (required) - User token for authentication
+ Response 200 (application/json)

    + Headers

            Location: /messages

    + Body

            {
            "status": 200,
            "data": [{
            "mail": {
                "id": 1,
                "createdOn": "05, April 2018",
                "subject": "Heello",
                "message": "Nice",
                "parentMessageId": "2",
                "status": "draft",
                "email": "ochowoikongbeh@gmail.com"
            }
            }
            ]
            }
            }
### Delete Redflag [DELETE]
* Delete specified redflag
+ Parameters
    + id (required, number, `1`) - Redflag id
    + token (required) - User token for authentication
+ Response 200 (application/json)

        {
        "status": 200,
        "data": "email deleted succesfully"
        }