swagger: '2.0'
info:
  version: '1.0'
  title: Epic Mail
  description: A web app that helps people exchange messages/information over the internet.
  contact: {}
host: epic-mail04.herokuapp.com
basePath: /api/v1
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /auth/login:
    post:
      description: 'TODO: Add Description'
      summary: login
      tags:
      - Users
      operationId: AuthLoginPost
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: email
        in: formData
        required: true
        type: string
        description: ''
      - name: password
        in: formData
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
  /auth/signup:
    post:
      description: 'TODO: Add Description'
      summary: signup
      tags:
      - Users
      operationId: AuthSignupPost
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: firstName
        in: formData
        required: true
        type: string
        description: ''
      - name: email
        in: formData
        required: true
        type: string
        description: ''
      - name: password
        in: formData
        required: true
        type: string
        description: ''
      - name: confirmPassword
        in: formData
        required: true
        type: string
        description: ''
      - name: lastName
        in: formData
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
  /messages:
    get:
      description: 'TODO: Add Description'
      summary: get messages
      tags:
      - Messages
      operationId: MessagesGet
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
    post:
      description: send email
      summary: create message
      tags:
      - Messages
      operationId: MessagesPost
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      - name: subject
        in: formData
        required: true
        type: string
        description: ''
      - name: message
        in: formData
        required: true
        type: string
        description: ''
      - name: receiverEmail
        in: formData
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
  /messages/unread:
    get:
      description: 'TODO: Add Description'
      summary: get unread messages
      tags:
      - Messages
      operationId: MessagesUnreadGet
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
  /messages/sent:
    get:
      description: 'TODO: Add Description'
      summary: get sent messages
      tags:
      - Messages
      operationId: MessagesSentGet
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
  /messages/1:
    get:
      description: 'TODO: Add Description'
      summary: get specific message
      tags:
      - Messages
      operationId: Messages1Get
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
    delete:
      description: 'TODO: Add Description'
      summary: delete a message
      tags:
      - Messages
      operationId: Messages1Delete
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
  /groups:
    post:
      description: 'TODO: Add Description'
      summary: create groups
      tags:
      - Groups
      operationId: GroupsPost
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: name
        in: formData
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
    get:
      description: 'TODO: Add Description'
      summary: get groups
      tags:
      - Groups
      operationId: GroupsGet
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
  /groups/1/name:
    patch:
      description: 'TODO: Add Description'
      summary: patch group name
      tags:
      - Groups
      operationId: Groups1NamePatch
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: name
        in: formData
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
  /groups/1:
    delete:
      description: 'TODO: Add Description'
      summary: delete group
      tags:
      - Groups
      operationId: Groups1Delete
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: name
        in: formData
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
  /groups/2/users:
    post:
      description: 'TODO: Add Description'
      summary: add a user to a group
      tags:
      - Groups
      operationId: Groups2UsersPost
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: email
        in: formData
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
  /groups/2/users/1:
    delete:
      description: 'TODO: Add Description'
      summary: delete a user from a group
      tags:
      - Groups
      operationId: Groups2Users1Delete
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: email
        in: formData
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
  /groups/2/messages:
    post:
      description: 'TODO: Add Description'
      summary: send message to a group
      tags:
      - Groups
      operationId: Groups2MessagesPost
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: x-access-token
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: subject
        in: formData
        required: true
        type: string
        description: ''
      - name: message
        in: formData
        required: true
        type: string
        description: ''
      - name: parentMessageId
        in: formData
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
tags:
- name: Users
  description: User Signup/Signin
- name: Messages
  description: ''
- name: Groups
  description: ''